name: DevSecOps Security Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep for SAST
        run: |
          semgrep --config auto --error .

      - name: Install OWASP Dependency-Check
        run: |
          curl -sSL -o dependency-check-12.1.0-release.zip https://github.com/dependency-check/dependency-check/releases/download/v12.1.0/dependency-check-12.1.0-release.zip
          unzip dependency-check-12.1.0-release.zip -d dependency-check
          chmod +x dependency-check/bin/dependency-check.sh

      - name: Scan Dependencies with OWASP Dependency-Check
        run: |
          dependency-check/bin/dependency-check.sh --project "DevSecOps Demo" --scan . --format "ALL" --failOnCVSS 5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image for Trivy scan
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: devsecops-demo

      - name: Install Trivy
        run: |
          curl -sSfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Scan Docker image with Trivy
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL devsecops-demo
