name: DevSecOps Security Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Semgrep Install Script
        run: |
          curl -sSL -o install_semgrep.sh https://semgrep.dev/install.sh

      - name: Check HTTP Status
        run: |
          curl -I https://semgrep.dev/install.sh

      - name: Check Script Contents
        run: |
          head -n 10 install_semgrep.sh

      - name: Install Semgrep
        run: |
          if grep -q "#!/bin/bash" install_semgrep.sh; then
            bash install_semgrep.sh
          else
            echo "Error: install_semgrep.sh is not a valid script."
            exit 1
          fi

      - name: Run Semgrep for SAST
        run: |
          semgrep --config auto --error .

      - name: Scan Dependencies with OWASP Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v7.7.1/dependency-check-7.7.1-release.zip
          unzip dependency-check-7.7.1-release.zip -d dependency-check
          chmod +x dependency-check/bin/dependency-check.sh
          dependency-check/bin/dependency-check.sh --project "DevSecOps Demo" --scan . --format "ALL" --failOnCVSS 5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image for Trivy scan
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: devsecops-demo

      - name: Install Trivy
        run: |
          curl -sSfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Scan Docker image with Trivy
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL devsecops-demo
